name: sugar
channels:
  - pytorch3d
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cmake>=3.26
  - ninja
  - pytorch=2.4.1=py3.10_cuda12.1_cudnn9.1.0_0
  - torchvision=0.19.1
  - torchaudio=2.4.1
  - pytorch-cuda=12.1
  - pytorch3d=0.7.8=py310_cu121_pyt241
  - cuda-toolkit=12.1
  - cuda-nvcc=12.1
  - fvcore>=0.1.5
  - iopath>=0.1.10
  - rich>=13.7
  - plotly>=5.19
  - plyfile=0.8.1
  - jupyterlab>=4.1
  - nodejs>=18,<19
  - ipywidgets>=8.1
  - scipy>=1.11
  - scikit-learn>=1.3
  - pandas>=2.1
  - tqdm>=4.66
  - requests>=2.31
  - pillow>=10.0
  - yacs>=0.1.8
  - tabulate>=0.9
  - yaml>=0.2.5
  - numpy>=1.26,<2
  - pyyaml>=6.0
  - setuptools>=68
  - wheel>=0.41
  - pip:
      - open3d==0.18.0
      - pymcubes>=0.1.4
      - dash>=2.14
      - dash-core-components>=2.0.0
      - dash-html-components>=2.0.0
      - dash-table>=5.0.0
      - flask>=3.0
      - itsdangerous>=2.1
      - werkzeug>=3.0
      - click>=8.1
      - addict>=2.4.0
      - pyquaternion>=0.9.9
      - nbformat>=5.9
